#!/bin/bash

# Colors for terminal output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=========================================${NC}"
echo -e "${GREEN}Starting AI-Powered LMS Platform${NC}"
echo -e "${BLUE}=========================================${NC}"

# Check if the API server is already running
if lsof -ti:8000 > /dev/null ; then
    echo -e "${YELLOW}Port 8000 is already in use. Stopping existing process...${NC}"
    lsof -ti:8000 | xargs kill -9
    echo "Existing process stopped."
fi

# Check if web server is already running
if lsof -ti:5500 > /dev/null ; then
    echo -e "${YELLOW}Port 5500 is already in use. Stopping existing process...${NC}"
    lsof -ti:5500 | xargs kill -9
    echo "Existing process stopped."
fi

# Create logs directory if it doesn't exist
mkdir -p logs

# Start FastAPI server in the background
echo -e "${GREEN}Starting FastAPI server on port 8000...${NC}"
# Make sure to use the Python from the virtual environment
if [ -d "lmsenv" ]; then
    source lmsenv/bin/activate
    echo "Activated virtual environment"
fi

# Start the API server (FastAPI)
# Using stdbuf to disable buffering on stdout for more immediate log entries
stdbuf -o0 python -m uvicorn app:app --host 0.0.0.0 --port 8000 --reload > logs/api_server.log 2>&1 &
API_PID=$!
echo "API server started with PID: $API_PID"
echo "Logs will be written in real-time to logs/api_server.log"
sleep 2  # Give the API server time to start

# Start ngrok with static domain in the background - ONLY for the API server
echo -e "${GREEN}Starting ngrok tunnel for API server with static domain...${NC}"
ngrok http 8000 --domain lively-intimate-treefrog.ngrok-free.app > logs/ngrok.log 2>&1 &
NGROK_PID=$!
echo "ngrok tunnel started with PID: $NGROK_PID"

# Update the web interface configuration
echo -e "${GREEN}Setting up web interface to use the ngrok domain...${NC}"
# Create a temporary config file for the web interface
cat > web_test/config.js <<EOL
// Generated by start script - DO NOT EDIT MANUALLY
const API_CONFIG = {
  apiUrl: 'https://lively-intimate-treefrog.ngrok-free.app',
  localApiUrl: 'http://localhost:8000',
  timestamp: '$(date)'
};
EOL

# Start web server in the background
echo -e "${GREEN}Starting web interface on port 5500...${NC}"
cd web_test && python -m http.server 5500 > ../logs/web_server.log 2>&1 &
WEB_PID=$!
echo "Web server started with PID: $WEB_PID"
cd ..

# Wait a bit for services to stabilize
sleep 2

# Test the API connection
echo -e "${YELLOW}Testing API connection...${NC}"
API_RESPONSE=$(curl -s http://localhost:8000/ || echo "Failed to connect")
if [[ "$API_RESPONSE" == *"LMS API is running"* ]]; then
  echo -e "${GREEN}✅ API server is responding correctly${NC}"
else
  echo -e "${YELLOW}⚠️ API server response check failed. Check logs for details.${NC}"
fi

# Create a file to store PIDs for later cleanup
mkdir -p logs
echo "$API_PID $NGROK_PID $WEB_PID" > logs/process_ids.txt

echo -e "${BLUE}=========================================${NC}"
echo -e "${GREEN}LMS System is now running!${NC}"
echo -e "${BLUE}=========================================${NC}"
echo -e "🌐 Web Interface: ${YELLOW}http://localhost:5500${NC}"
echo -e "🔌 Local API Endpoint: ${YELLOW}http://localhost:8000${NC}"
echo -e "🌍 Public API URL: ${YELLOW}https://lively-intimate-treefrog.ngrok-free.app${NC}"
echo -e "${BLUE}=========================================${NC}"
echo -e "📝 Logs are stored in the logs directory"
echo -e "❗ To stop all services, run ${YELLOW}./stop_lms.sh${NC}"
echo -e "${BLUE}=========================================${NC}"
echo -e "⚠️  IMPORTANT: Your web interface should use the API at ${YELLOW}https://lively-intimate-treefrog.ngrok-free.app${NC}"
echo -e "${BLUE}=========================================${NC}"
